// vue/src/components/navigation-menu/NavigationMenuItem.vue
<script lang="ts">
import type { HTMLAttributes } from "vue";

export interface NavigationMenuItemProps {
	/** This item's value — what `NavigationMenu`'s `value` becomes while its panel is open. */
	value: string;
	/** Additional CSS classes. */
	class?: HTMLAttributes["class"];
}
</script>

<script setup lang="ts">
import { cn } from "../../utils.js";
import { useFancyId } from "../../internals/use-id.js";
import { NAVIGATION_MENU_ITEM_KEY, type NavigationMenuItemContext } from "./types.js";

/**
 * One disclosure in the row: its trigger, its panel, and the identity that
 * ties the two together. The source exposes no ref here, so neither does this.
 */
defineOptions({ name: "NavigationMenuItem", inheritAttrs: false });

const { value, class: className } = defineProps<NavigationMenuItemProps>();

defineSlots<{
	/** A `NavigationMenuTrigger` + `NavigationMenuContent` pair. */
	default?: () => unknown;
}>();

// Stable across SSR and hydration — `uid()` throws on the server, and the
// trigger's `aria-controls` / the panel's `aria-labelledby` need to agree with
// themselves from the first server-rendered paint (convention C-6).
const baseId = useFancyId();

const context: NavigationMenuItemContext = {
	get value() {
		return value;
	},
	get triggerId() {
		return `${baseId}-trigger`;
	},
	get contentId() {
		return `${baseId}-content`;
	},
};
NAVIGATION_MENU_ITEM_KEY.provide(context);
</script>

<template>
	<li :class="cn('ft-navigation-menu-item', className)">
		<slot />
	</li>
</template>

// src/lib/fancy-ui/navigation-menu/NavigationMenuItem.svelte
<script lang="ts" module>
	import type { Snippet } from "svelte";

	export interface NavigationMenuItemProps {
		/** This item's value — what `NavigationMenu`'s `value` becomes while its panel is open. */
		value: string;
		/** A `NavigationMenuTrigger` + `NavigationMenuContent` pair. */
		children?: Snippet;
		/** Additional CSS classes. */
		class?: string;
	}
</script>

<script lang="ts">
	import { setContext } from "svelte";
	import { cn } from "$lib/utils.js";
	import { NAVIGATION_MENU_ITEM_KEY, type NavigationMenuItemContext } from "./types.js";

	let { value, children, class: className }: NavigationMenuItemProps = $props();

	// Stable across SSR and hydration — `_internals/id.js`'s `uid()` throws
	// on the server, and the trigger's `aria-controls` / the panel's
	// `aria-labelledby` need to agree with themselves from the first
	// server-rendered paint.
	const baseId = $props.id();

	const context: NavigationMenuItemContext = {
		get value() {
			return value;
		},
		get triggerId() {
			return `${baseId}-trigger`;
		},
		get contentId() {
			return `${baseId}-content`;
		},
	};
	setContext(NAVIGATION_MENU_ITEM_KEY, context);
</script>

<li class={cn("ft-navigation-menu-item", className)}>
	{@render children?.()}
</li>
