// src/lib/fancy-ui/book/BookDescription.svelte
<script lang="ts">
	import { cn } from "$lib/utils";
	import type { Snippet } from "svelte";

	interface Props {
		class?: string;
		children?: Snippet;
	}

	let { class: className = "", children }: Props = $props();
</script>

<p class={cn("text-xs/relaxed select-none", className)}>
	{#if children}
		{@render children()}
	{/if}
</p>

// react/src/components/book/BookDescription.tsx
import type { HTMLAttributes, ReactNode } from "react";
import { cn } from "../../utils.js";

export interface BookDescriptionProps extends Omit<HTMLAttributes<HTMLParagraphElement>, "className"> {
	className?: string;
	children?: ReactNode;
}

export function BookDescription({ className = "", children, ...rest }: BookDescriptionProps) {
	return (
		<p className={cn("text-xs/relaxed select-none", className)} {...rest}>
			{children}
		</p>
	);
}
