// vue/src/components/book/BookHeader.vue
<script lang="ts">
import type { HTMLAttributes } from "vue";

/**
 * Props for BookHeader
 */
export interface BookHeaderProps {
	class?: HTMLAttributes["class"];
}
</script>

<script setup lang="ts">
import { cn } from "../../utils.js";

defineOptions({ name: "BookHeader", inheritAttrs: false });

const props = withDefaults(defineProps<BookHeaderProps>(), {
	class: "",
});
</script>

<template>
	<div :class="cn('flex flex-wrap gap-2', props.class)">
		<slot></slot>
	</div>
</template>

// react/src/components/book/BookHeader.tsx
import type { HTMLAttributes, ReactNode } from "react";
import { cn } from "../../utils.js";

export interface BookHeaderProps extends Omit<HTMLAttributes<HTMLDivElement>, "className"> {
	className?: string;
	children?: ReactNode;
}

export function BookHeader({ className = "", children, ...rest }: BookHeaderProps) {
	return (
		<div className={cn("flex flex-wrap gap-2", className)} {...rest}>
			{children}
		</div>
	);
}
