// src/lib/fancy-ui/book/BookHeader.svelte
<script lang="ts">
	import { cn } from "$lib/utils";
	import type { Snippet } from "svelte";

	interface Props {
		class?: string;
		children?: Snippet;
	}

	let { class: className = "", children }: Props = $props();
</script>

<div class={cn("flex flex-wrap gap-2", className)}>
	{#if children}
		{@render children()}
	{/if}
</div>

// react/src/components/book/BookHeader.tsx
import type { HTMLAttributes, ReactNode } from "react";
import { cn } from "../../utils.js";

export interface BookHeaderProps extends Omit<HTMLAttributes<HTMLDivElement>, "className"> {
	className?: string;
	children?: ReactNode;
}

export function BookHeader({ className = "", children, ...rest }: BookHeaderProps) {
	return (
		<div className={cn("flex flex-wrap gap-2", className)} {...rest}>
			{children}
		</div>
	);
}
