// react/src/cameleon/primitives/Badge.tsx
import type { ReactNode } from "react";
import { cn } from "../../utils.js";
import { useSkin } from "../context.js";
import type { PartState } from "../types.js";

export interface BadgeProps {
	variant?: "default" | "solid" | "blue" | "red" | "yellow" | "green" | "purple";
	/** Force a visual state for the /skins state matrix. */
	demoState?: PartState;
	className?: string;
	children?: ReactNode;
}

export function Badge({ variant = "default", demoState, className, children }: BadgeProps) {
	const ctx = useSkin();
	const parts = ctx.skin.recipes.badge({ variant, state: demoState });

	return <span className={cn(parts.root, className)}>{children}</span>;
}

// vue/src/cameleon/primitives/Badge.vue
<script lang="ts">
import type { HTMLAttributes } from "vue";
import type { PartState } from "../types.js";

export interface BadgeProps {
	variant?: "default" | "solid" | "blue" | "red" | "yellow" | "green" | "purple";
	/** Force a visual state for the /skins state matrix. */
	demoState?: PartState;
	class?: HTMLAttributes["class"];
}
</script>

<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../../utils.js";
import { useSkin } from "../context.js";

defineOptions({ name: "Badge", inheritAttrs: false });

const { variant = "default", demoState, class: className } = defineProps<BadgeProps>();

defineSlots<{ default?: () => unknown }>();

const ctx = useSkin();
const parts = computed(() => ctx.skin.recipes.badge({ variant, state: demoState }));
</script>

<template>
	<span :class="cn(parts.root, className)"><slot /></span>
</template>
