// react/src/components/autocomplete/AutocompletePanel.tsx
import { useCallback, useRef } from "react";
import type { MouseEvent } from "react";

import { cn } from "../../utils.js";
import { Portal } from "../../internals/Portal.js";
import { useAnchorPosition } from "../../internals/use-anchor-position.js";
import { useDismissable } from "../../internals/dismissable.js";
import { useComposedRefs } from "../../internals/dom/use-composed-refs.js";
import { useElementRef } from "../../internals/dom/use-element-ref.js";
import { anchored, originFor } from "../../internals/motion/anchored.js";
import { usePresence } from "../../internals/motion/presence.js";
import { getMatchRange } from "./match.js";
import { AUTOCOMPLETE_KEY } from "./types.js";

/**
 * The floating suggestions list.
 *
 * `Autocomplete` renders this unconditionally and it gates itself on
 * `ctx.open`, where the source mounts it inside its own `{#if open}` — so the
 * context is always present, and the rows are never drawn before there is at
 * least one suggestion to show.
 */
export function AutocompletePanel() {
	const ctx = AUTOCOMPLETE_KEY.useRequired();

	// Convention C-1: the NODE, not a ref. The panel is created by
	// `presence.mounted`, so a `useRef` + `[]`-deps effect would still be
	// holding `null` when the positioning and dismissable effects fire.
	const [panel, setPanelNode] = useElementRef<HTMLDivElement>();

	const presence = usePresence(ctx.open);

	// The side and alignment the panel was ACTUALLY placed on. This panel
	// always asks for `"bottom"` / `"start"`, but an input sitting low in the
	// viewport flips the side to `"top"`, and near a viewport edge clamping
	// slides the panel along the cross axis — the entrance origin has to
	// follow both, or it grows from the far corner. Seeded with the requested
	// values, so the un-flipped case never depends on a placement callback
	// having fired first.
	const { side, align } = useAnchorPosition(panel, {
		anchor: () => ctx.inputRef,
		side: "bottom",
		align: "start",
		offset: 4,
	});

	const exclude = useCallback(() => [ctx.inputRef], [ctx.inputRef]);

	// `active: ctx.open` — a plain boolean where the source needed a getter.
	// The layer stays ON the stack for its whole exit and stops being TOP of it
	// the instant `open` flips, so a second Escape during the fade falls
	// through to whatever is underneath instead of being swallowed by a panel
	// that is already leaving.
	useDismissable(panel, { onDismiss: ctx.close, exclude, active: ctx.open });

	// Convention C-2: composed ABOVE the conditional below. Calling this inside
	// the presence gate would be a conditional hook and would throw the first
	// time `mounted` flips.
	//
	// ONE bidirectional transition, never a split in/out pair: a list reopened
	// mid-exit is handed the in-flight leg as its counterpart and continues
	// from where it is instead of snapping to invisible first. That matters
	// more here than anywhere else in the family, because a suggestion list
	// closes and reopens on keystrokes — a query that stops matching closes it,
	// and the next character that matches again reverses the exit already in
	// flight.
	const panelRef = useComposedRefs(
		setPanelNode,
		presence.register(anchored, (entering) => ({ side, entering }))
	);

	// Svelte destroys the `{#if open}` branch that owns this component, and
	// marks it INERT before playing the outro — its scheduler skips inert
	// effects, so the rows on screen during the exit are frozen at whatever
	// they were the instant the close began. React re-renders an exiting
	// subtree normally, so the freeze is explicit here: without it a list that
	// closed BECAUSE its query stopped matching would empty itself to a bare
	// box halfway through its own fade, which is the single most common way
	// this particular panel closes.
	const frozen = useRef({
		suggestions: ctx.suggestions,
		query: ctx.query,
		activeIndex: ctx.activeIndex,
	});
	if (ctx.open) {
		frozen.current = {
			suggestions: ctx.suggestions,
			query: ctx.query,
			activeIndex: ctx.activeIndex,
		};
	}
	const view = frozen.current;

	// The `Portal` stays mounted and its CHILDREN are what `presence.mounted`
	// gates: `usePortalTarget` resolves its container in a layout effect, so a
	// `Portal` mounting in the same commit as the surface renders nothing on
	// that pass — and the registered node would therefore not exist yet when
	// `usePresence` looks for legs to start, which settles the group
	// immediately and skips the entrance outright.
	return (
		<Portal>
			{presence.mounted ? (
				/*
					A `<div role="listbox">`, not a `<ul>` — see Combobox's identical
					panel for why (its rows are real buttons, not a permitted child of
					`<ul>`).

					No focus trap: focus never leaves the input (`aria-activedescendant`
					tracks the active row instead). Each row is a real button, kept out
					of the tab sequence with `tabindex="-1"`, with `onMouseDown` calling
					`preventDefault()` so clicking one never blurs the input a beat
					before its own `onClick` commits the suggestion.

					`data-state` is an ordinary attribute (divergence D-2) carrying
					`surfaceState`'s TWO values — never `"opening"` (convention C-5).
					`inert` is not written by hand either: `usePresence` sets it on the
					registered node for the whole exit, which is what stops a row taking
					a click on its way out.
				*/
				<div
					ref={panelRef}
					id={ctx.panelId}
					role="listbox"
					className="ft-autocomplete-panel border-border bg-popover text-popover-foreground flex max-h-[260px] w-max min-w-[220px] flex-col gap-[1px] overflow-auto rounded-[10px] border p-[5px] text-[13px] shadow-lg outline-none"
					data-state={presence.surfaceState}
					data-side={side}
					data-align="start"
					style={{ transformOrigin: originFor(side, align) }}
				>
					{view.suggestions.map((suggestion, index) => {
						const range = getMatchRange(suggestion, view.query);
						const isActive = index === view.activeIndex;
						return (
							/*
								`onMouseDown` below defends against a real browser's
								focus-follows-mousedown default action stealing focus onto
								this row before its own `onClick` commits — without it, that
								focus shift blurs the input first, which closes the panel
								(unmounting this row) before the click already in flight can
								land. jsdom implements no such default action to suppress, so
								no test in this repo can watch this guard prevent that
								outcome — only that the call happens (the suite's "the row's
								mousedown handler calls preventDefault" dispatches a bare
								`mousedown` and checks `event.defaultPrevented`). Do not
								delete this as dead code on the strength of a green suite.
							*/
							<button
								key={suggestion}
								type="button"
								id={ctx.optionId(index)}
								role="option"
								tabIndex={-1}
								aria-selected={isActive}
								className={cn(
									"ft-autocomplete-option flex w-full cursor-pointer items-center justify-between gap-2 rounded-[6px] px-[10px] py-[7px] text-left",
									isActive && "bg-accent text-accent-foreground"
								)}
								onMouseDown={(event: MouseEvent<HTMLButtonElement>) => event.preventDefault()}
								onClick={() => ctx.select(suggestion)}
							>
								<span>
									{range ? (
										<>
											{suggestion.slice(0, range.start)}
											<strong>{suggestion.slice(range.start, range.end)}</strong>
											{suggestion.slice(range.end)}
										</>
									) : (
										suggestion
									)}
								</span>
								{isActive ? (
									<kbd aria-hidden="true" className="text-muted-foreground font-mono text-[10px]">
										⏎
									</kbd>
								) : null}
							</button>
						);
					})}
				</div>
			) : null}
		</Portal>
	);
}

AutocompletePanel.displayName = "AutocompletePanel";

// src/lib/fancy-ui/autocomplete/AutocompletePanel.svelte
<script lang="ts">
	import { getContext } from "svelte";
	import { cn } from "$lib/utils.js";
	import { anchorPosition, type Side, type Align } from "../_internals/anchor-position.js";
	import { portal } from "../_internals/portal.js";
	import { dismissable } from "../_internals/dismissable.js";
	import { anchored, markSurfaceState, originFor } from "../_internals/motion/anchored.js";
	import { getMatchRange } from "./match.js";
	import { AUTOCOMPLETE_KEY, type AutocompleteContext } from "./types.js";

	// `Autocomplete` only ever mounts this component inside its own
	// `{#if open}`, and only once there is at least one suggestion to show —
	// so the context is always present, and `suggestions` is never empty,
	// by the time this runs.
	const ctx = getContext<AutocompleteContext>(AUTOCOMPLETE_KEY);

	// The side the panel was ACTUALLY placed on. This panel always asks for
	// `"bottom"`, but an input sitting low in the viewport flips it to
	// `"top"`, and the entrance origin has to follow — see Combobox's
	// identical panel. Seeded with the requested side so the un-flipped case
	// never depends on `onPlacement` having fired first.
	let resolvedSide = $state<Side>("bottom");

	// The cross-axis alignment as ACTUALLY placed, reported by `anchorPosition`
	// alongside the side. It differs from the requested alignment whenever
	// clamping slid the panel along that axis — near a viewport edge the
	// requested corner is no longer the one touching the anchor, and an
	// entrance grown from it would expand from the far corner instead.
	let resolvedAlign = $state<Align>("start");
</script>

<!--
	A `<div role="listbox">`, not a `<ul>` — see Combobox's identical panel
	for why (its rows are real buttons, not a permitted child of `<ul>`).

	No focus trap: focus never leaves the input (`aria-activedescendant`
	tracks the active row instead). Each row is a real button, kept out of
	the tab sequence with `tabindex="-1"`, with `onmousedown` calling
	`preventDefault()` so clicking one never blurs the input a beat before
	its own `onclick` commits the suggestion.

	This panel had no motion at all until recently — it appeared and vanished
	fully formed while every sibling surface rose into place. It now arrives and
	leaves on ONE bidirectional `transition:`, never a split `in:`/`out:` pair:
	a bidirectional directive hands the in-flight counterpart's current position
	to the fresh call, so a list reopened mid-exit continues from where it is
	instead of snapping to invisible first. That matters more here than
	anywhere else in the family, because a suggestion list closes and reopens
	on keystrokes — a query that stops matching closes it, and the next
	character that matches again reverses the exit already in flight.

	`entering: ctx.open` is what tells it which way it is going — Svelte reports
	`direction: "both"` for one bidirectional directive and cannot tell the two
	apart on its own, and the `{#if}` that mounts this component lives one level
	up in `Autocomplete`, so the flag has to arrive through the context.

	`data-state` is a STATIC literal, changed only by `markSurfaceState` from
	the two handlers below. Svelte marks this branch inert before it plays the
	outro and the scheduler skips inert effects, so a reactive `data-state={…}`
	would never reach the DOM on a real close. `inert` itself is never written
	by hand: Svelte sets it on any element carrying a `transition:` for the
	whole exit, which is what stops a row taking a click on its way out.
-->
<div
	id={ctx.panelId}
	role="listbox"
	class="ft-autocomplete-panel border-border bg-popover text-popover-foreground flex max-h-[260px] w-max min-w-[220px] flex-col gap-[1px] overflow-auto rounded-[10px] border p-[5px] text-[13px] shadow-lg outline-none"
	use:portal
	use:anchorPosition={{
		anchor: () => ctx.inputRef,
		side: "bottom",
		align: "start",
		offset: 4,
		onPlacement: (side, align) => {
			resolvedSide = side;
			resolvedAlign = align;
		},
	}}
	use:dismissable={{
		onDismiss: ctx.close,
		exclude: () => [ctx.inputRef],
		active: () => ctx.open,
	}}
	transition:anchored={{ side: resolvedSide, entering: ctx.open }}
	data-state="open"
	data-side={resolvedSide}
	data-align="start"
	style:transform-origin={originFor(resolvedSide, resolvedAlign)}
	onintrostart={(e) => markSurfaceState(e, "open")}
	onoutrostart={(e) => markSurfaceState(e, "closing")}
>
	{#each ctx.suggestions as suggestion, index (suggestion)}
		{@const range = getMatchRange(suggestion, ctx.query)}
		<!-- `onmousedown` below defends against a real browser's
		     focus-follows-mousedown default action stealing focus onto this row
		     before its own `onclick` commits — without it, that focus shift
		     blurs the input first, which closes the panel (unmounting this row)
		     before the click already in flight can land. jsdom implements no
		     such default action to suppress, so no test in this repo can watch
		     this guard prevent that outcome — only that the call happens
		     (`Autocomplete.test.ts`'s "the row's mousedown handler calls
		     preventDefault" dispatches a bare `mousedown` and checks
		     `event.defaultPrevented`). Do not delete this as dead code on the
		     strength of a green suite. -->
		<button
			type="button"
			id={ctx.optionId(index)}
			role="option"
			tabindex="-1"
			aria-selected={ctx.isActive(index)}
			class={cn(
				"ft-autocomplete-option flex w-full cursor-pointer items-center justify-between gap-2 rounded-[6px] px-[10px] py-[7px] text-left",
				ctx.isActive(index) && "bg-accent text-accent-foreground"
			)}
			onmousedown={(event) => event.preventDefault()}
			onclick={() => ctx.select(suggestion)}
		>
			<span>
				{#if range}
					{suggestion.slice(0, range.start)}<strong
						>{suggestion.slice(range.start, range.end)}</strong
					>{suggestion.slice(range.end)}
				{:else}
					{suggestion}
				{/if}
			</span>
			{#if ctx.isActive(index)}
				<kbd aria-hidden="true" class="text-muted-foreground font-mono text-[10px]">⏎</kbd>
			{/if}
		</button>
	{/each}
</div>
