// src/lib/fancy-ui/_internals/StreamText.svelte
<script lang="ts" module>
	/**
	 * Props for StreamText
	 */
	export interface StreamTextProps {
		/** The whole text so far. Hand over a longer string to stream more in. */
		text: string;
		/** How long a newly arrived chunk stays tinted, in ms. */
		settleMs?: number;
		/** Additional CSS classes */
		class?: string;
	}
</script>

<script lang="ts">
	import { onDestroy, untrack } from "svelte";
	import { cn } from "$lib/utils.js";
	import { createTextStream } from "./stream-text.svelte.js";

	let { text, settleMs = 350, class: className }: StreamTextProps = $props();

	// Built once, with the initial text already settled: the server renders the
	// whole string as a single plain span and only later growth animates. Reading
	// the text here is meant to capture its first value, hence the untrack —
	// `settleMs` goes in as a getter so a later duration reaches later chunks
	// instead of leaving them on the mount-time timeout the CSS no longer matches.
	const stream = untrack(() => createTextStream(text, { settleMs: () => settleMs }));

	// The first run pushes the text the stream was built from, which is a no-op.
	$effect(() => {
		stream.push(text);
	});

	onDestroy(() => stream.destroy());
</script>

<span class={cn("ft-stream", className)} style="white-space: pre-wrap; --ft-settle: {settleMs}ms"
	>{#each stream.segments as segment (segment.id)}<span class:ft-fresh={segment.fresh}
			>{segment.text}</span
		>{/each}</span
>

<style>
	/*
	 * Reduced motion gets plain text at its final colour: with the whole rule
	 * behind the query there is no animation to shorten or fall back from.
	 */
	@media (prefers-reduced-motion: no-preference) {
		.ft-fresh {
			animation: ft-tint var(--ft-settle, 350ms) ease-out;
		}

		@keyframes ft-tint {
			from {
				color: var(--ft-tint-color, oklch(0.65 0.15 250));
				opacity: 0.6;
			}
			to {
				color: inherit;
				opacity: 1;
			}
		}
	}
</style>

// react/src/internals/StreamText.tsx
import type { CSSProperties, JSX } from "react";
import { cn } from "../utils.js";
import { useLiveRef } from "./dom/use-live-ref.js";
import { useIsomorphicLayoutEffect } from "./dom/ssr.js";
import { useTextStream } from "./use-text-stream.js";
import "./stream-text.css";

export interface StreamTextProps {
	/** The whole text so far. Hand over a longer string to stream more in. */
	text: string;
	/** How long a newly arrived chunk stays tinted, in ms. */
	settleMs?: number;
	/** Additional CSS classes */
	className?: string;
}

/**
 * Renders `text`, tinting only the delta between renders while it settles.
 *
 * Built once from the first `text`/`settleMs` it sees — the server renders
 * the whole string as a single plain span, and only later growth animates —
 * mirroring the Svelte source's `untrack(() => createTextStream(...))`. The
 * push that reconciles the stream with a new `text` runs in a layout effect,
 * before paint, so a re-render never flashes the previous content for a
 * frame.
 */
export function StreamText({ text, settleMs = 350, className }: StreamTextProps): JSX.Element {
	// A live getter, read once per pushed chunk (never during render), so a
	// later `settleMs` reaches later chunks instead of only the CSS custom
	// property.
	const settleMsRef = useLiveRef(settleMs);
	const { segments, push } = useTextStream(text, { settleMs: () => settleMsRef.current });

	useIsomorphicLayoutEffect(() => {
		// The first run pushes the text the stream was built from, which is a
		// no-op.
		push(text);
	}, [text, push]);

	return (
		<span
			className={cn("ft-stream", className)}
			style={{ whiteSpace: "pre-wrap", ["--ft-settle" as string]: `${settleMs}ms` } as CSSProperties}
		>
			{segments.map((segment) => (
				<span key={segment.id} className={segment.fresh ? "ft-fresh" : undefined}>
					{segment.text}
				</span>
			))}
		</span>
	);
}
