// react/src/components/dock/DockSeparator.tsx
import { cn } from "../../utils.js";
import { useDockContext } from "./types.js";

export interface DockSeparatorProps {
	/** Additional CSS classes */
	className?: string;
}

/** A rule between two groups of dock icons, laid across the dock's own axis. */
export function DockSeparator({ className = "" }: DockSeparatorProps) {
	const context = useDockContext();

	return (
		<div
			className={cn(
				"bg-secondary relative block",
				context.orientation === "vertical" ? "h-0.5 w-4/5" : "h-4/5 w-0.5",
				className
			)}
		/>
	);
}

// src/lib/inspira/dock/DockSeparator.svelte
<script lang="ts">
	import { getContext } from 'svelte';
	import { cn } from '$lib/utils';
	import { DOCK_CONTEXT_KEY, type DockContext } from './types';

	interface Props {
		class?: string;
	}

	let { class: className = '' }: Props = $props();

	const context = getContext<DockContext>(DOCK_CONTEXT_KEY);
</script>

<div
	class={cn(
		'relative block bg-secondary',
		context.orientation === 'vertical' ? 'w-4/5 h-0.5' : 'h-4/5 w-0.5',
		className
	)}
></div>
