// react/src/components/animated-tooltip/AnimatedTooltip.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import type { CSSProperties, MouseEvent as ReactMouseEvent } from "react";

import { cn } from "../../utils.js";
import { useLiveRef } from "../../internals/dom/use-live-ref.js";
import { linear } from "../../internals/motion/easing.js";
import { useReducedMotion } from "../../internals/motion/media-query.js";
import { usePresence } from "../../internals/motion/presence.js";
import type { TransitionSpec } from "../../internals/motion/transitions.js";

import "./animated-tooltip.css";

export interface TooltipItem {
	id: number | string;
	name: string;
	designation: string;
	image: string;
}

export interface AnimatedTooltipProps {
	/** Array of items to display */
	items: TooltipItem[];
	/** Additional CSS classes for the container */
	className?: string;
	/**
	 * Tint of the presence ring and the light sweep under the name. Any CSS
	 * colour (`"#f5a97f"`, `"oklch(0.7 0.14 160)"`, `"var(--primary)"`).
	 * Leave unset for the default soft iridescent pair, which adapts to the
	 * light and dark themes.
	 */
	accent?: string;
	/** Avatar diameter in pixels. */
	size?: number;
}

type ItemId = number | string;

/** The id the tooltip is published under, so the wrapper can point
 *  `aria-describedby` at it while it is shown. */
function tooltipId(itemId: ItemId): string {
	return `animated-tooltip-${itemId}`;
}

/**
 * The inline transform the tooltip positioner is drawn at. `mouseX` is the
 * pointer's offset from the hovered avatar's centre, normalised by half the
 * avatar size to [-1, 1]: the card leans up to 7deg and slides up to 14px
 * toward the pointer; reduced motion keeps it upright.
 */
function transformFor(mouseX: number, size: number, reduced: boolean): string {
	const lean = reduced ? 0 : Math.max(-1, Math.min(1, mouseX / (size / 2)));
	const rotation = lean * 7;
	const translation = lean * 14;
	return `translateX(calc(-50% + ${translation}px)) rotate(${rotation}deg)`;
}

/** How far item `i` steps aside to make room for the active one. */
function partOffset(i: number, activeIndex: number, reduced: boolean): number {
	if (activeIndex < 0 || reduced) return 0;
	const d = i - activeIndex;
	const distance = Math.abs(d);
	if (distance === 1) return Math.sign(d) * 6;
	if (distance === 2) return Math.sign(d) * 2;
	return 0;
}

interface SinkParams {
	entering: boolean;
	still: boolean;
}

/**
 * Exit: a short settle downward (opacity only under reduced motion). The
 * source carries this as an exit-only transition, so the ENTER leg runs at
 * duration 0 — the card appears at rest and its entrance is the CSS
 * `at-rise` / `at-fade` keyframe, exactly as in the source. A reversal
 * mid-exit therefore snaps back to rest rather than replaying anything, which
 * is what an exit-only transition does when its block resumes.
 */
function sink(_node: Element, params?: SinkParams): TransitionSpec {
	if (!params || params.entering) {
		return { delay: 0, duration: 0, easing: linear, css: () => "" };
	}
	const still = params.still;
	return {
		delay: 0,
		duration: still ? 120 : 160,
		easing: (t: number) => t * t,
		css: (t: number) =>
			still
				? `opacity: ${t};`
				: `opacity: ${t}; transform: translateY(${(1 - t) * 4}px) scale(${0.97 + 0.03 * t});`,
	};
}

interface AvatarItemProps {
	item: TooltipItem;
	active: boolean;
	shift: number;
	reduced: boolean;
	onEnter: (itemId: ItemId, event: ReactMouseEvent<HTMLDivElement>) => void;
	onMove: (event: ReactMouseEvent<HTMLDivElement>) => void;
	onLeave: () => void;
	onFocusIn: (itemId: ItemId) => void;
	onTip: (itemId: ItemId, node: HTMLElement | null, previous: HTMLElement | null) => void;
}

/** One avatar and its conditional tooltip. A separate component because each
 *  item owns a presence clock (the mount/unmount timing the source's
 *  transition-aware conditional block owned natively). */
function AvatarItem({
	item,
	active,
	shift,
	reduced,
	onEnter,
	onMove,
	onLeave,
	onFocusIn,
	onTip,
}: AvatarItemProps) {
	const presence = usePresence(active);
	// Rewritten every render, read at the instant a leg starts: the source's
	// exit reads the reduced-motion flag when the outro begins.
	const cardRef = presence.register(sink, (entering) => ({ entering, still: reduced }));

	// The positioner is handed to the row, which alone writes its transform.
	// Block body, never a concise arrow: React 19 reads a returned value as a
	// cleanup function.
	const tipNode = useRef<HTMLElement | null>(null);
	const itemId = item.id;
	const attachTip = useCallback(
		(node: HTMLElement | null) => {
			if (node) {
				tipNode.current = node;
				onTip(itemId, node, null);
				return;
			}
			onTip(itemId, null, tipNode.current);
			tipNode.current = null;
		},
		[itemId, onTip]
	);

	return (
		<div
			className={cn("at-item group relative", active && "at-active", shift !== 0 && "at-parted")}
			style={{ "--_at-shift": `${shift}px` } as CSSProperties}
			data-active={active ? "" : undefined}
			data-part={shift < 0 ? "before" : shift > 0 ? "after" : undefined}
			onMouseEnter={(event) => onEnter(item.id, event)}
			onMouseLeave={onLeave}
			onMouseMove={onMove}
			onFocus={() => onFocusIn(item.id)}
			onBlur={onLeave}
			tabIndex={0}
			aria-describedby={active ? tooltipId(item.id) : undefined}
		>
			{/* Tooltip */}
			{presence.mounted && (
				<div
					ref={attachTip}
					id={tooltipId(item.id)}
					role="tooltip"
					className="at-tip pointer-events-none absolute left-1/2 z-50"
				>
					<div ref={cardRef} className="at-card">
						<span className="at-pointer" aria-hidden="true"></span>
						<div className="at-name">{item.name}</div>
						<span className="at-rule" aria-hidden="true">
							<span className="at-glint"></span>
						</span>
						<div className="at-role">{item.designation}</div>
					</div>
				</div>
			)}

			{/* Avatar: presence ring + photo */}
			<div className={cn("at-avatar", active && !reduced && "at-lifted")}>
				<span className="at-glow" aria-hidden="true"></span>
				<span className="at-disc" aria-hidden="true"></span>
				<span className="at-ring" aria-hidden="true"></span>
				<img
					src={item.image}
					alt={item.name}
					className="at-img relative !m-0 rounded-full object-cover object-top !p-0"
				/>
			</div>
		</div>
	);
}

export function AnimatedTooltip({ items, className, accent, size = 56 }: AnimatedTooltipProps) {
	const reduced = useReducedMotion();

	const [hoveredId, setHoveredId] = useState<ItemId | null>(null);

	/**
	 * The pointer offset, the hovered id as the handlers see it, and every
	 * mounted tooltip positioner. Refs, never state: the source reads the
	 * shared `mouseX` only INSIDE the active item's conditional block, so one
	 * pointer sample rewrites one style attribute on one node. Holding it in
	 * React state would re-render every avatar in the row on every mousemove.
	 *
	 * Writing only to the ACTIVE item's positioner is also what reproduces the
	 * source's freeze: a leaving block is paused, so its tooltip keeps the
	 * transform it was last drawn at while the pointer moves on — onto the
	 * overlapping neighbour or off the row, where `mouseX` resets to 0.
	 */
	const mouseX = useRef(0);
	const hovered = useRef<ItemId | null>(null);
	const tips = useRef(new Map<ItemId, HTMLElement>());
	const reducedRef = useLiveRef(reduced);
	const sizeRef = useLiveRef(size);

	const draw = useCallback(
		(itemId: ItemId): void => {
			const node = tips.current.get(itemId);
			if (node)
				node.style.transform = transformFor(mouseX.current, sizeRef.current, reducedRef.current);
		},
		[reducedRef, sizeRef]
	);

	const onTip = useCallback(
		(itemId: ItemId, node: HTMLElement | null, previous: HTMLElement | null): void => {
			if (node) {
				tips.current.set(itemId, node);
				// A freshly mounted positioner carries no transform yet.
				draw(itemId);
				return;
			}
			if (tips.current.get(itemId) === previous) tips.current.delete(itemId);
		},
		[draw]
	);

	const activate = useCallback(
		(itemId: ItemId): void => {
			hovered.current = itemId;
			setHoveredId(itemId);
			// A re-entry during the exit finds the positioner still mounted and
			// redraws it; a first entry finds none and `onTip` draws on mount.
			draw(itemId);
		},
		[draw]
	);

	const handleMouseEnter = useCallback(
		(itemId: ItemId, event: ReactMouseEvent<HTMLDivElement>): void => {
			// Reset mouseX first to prevent offset from previous item
			const rect = event.currentTarget.getBoundingClientRect();
			mouseX.current = event.clientX - rect.left - rect.width / 2;
			activate(itemId);
		},
		[activate]
	);

	const handleMouseMove = useCallback(
		(event: ReactMouseEvent<HTMLDivElement>): void => {
			if (hovered.current === null) return;
			const rect = event.currentTarget.getBoundingClientRect();
			mouseX.current = event.clientX - rect.left - rect.width / 2;
			draw(hovered.current);
		},
		[draw]
	);

	const handleLeave = useCallback((): void => {
		hovered.current = null;
		mouseX.current = 0;
		setHoveredId(null);
	}, []);

	const handleFocusIn = useCallback(
		(itemId: ItemId): void => {
			mouseX.current = 0;
			activate(itemId);
		},
		[activate]
	);

	// The source derives the lean from `size` and the reduced-motion flag, so
	// either changing redraws the active card.
	useEffect(() => {
		if (hovered.current !== null) draw(hovered.current);
	}, [draw, reduced, size]);

	/** Index of the active item, or -1 when nothing is hovered/focused. */
	const activeIndex = hoveredId === null ? -1 : items.findIndex((item) => item.id === hoveredId);

	const rootStyle = {
		"--_at-size": `${size}px`,
		...(accent
			? {
					"--at-accent": accent,
					"--at-accent-2": `color-mix(in oklab, ${accent} 62%, white)`,
				}
			: {}),
	} as CSSProperties;

	return (
		<div className={cn("at-root flex flex-row items-center", className)} style={rootStyle}>
			{items.map((item, i) => (
				<AvatarItem
					key={item.id}
					item={item}
					active={hoveredId === item.id}
					shift={partOffset(i, activeIndex, reduced)}
					reduced={reduced}
					onEnter={handleMouseEnter}
					onMove={handleMouseMove}
					onLeave={handleLeave}
					onFocusIn={handleFocusIn}
					onTip={onTip}
				/>
			))}
		</div>
	);
}

// src/lib/fancy-ui/animated-tooltip/AnimatedTooltip.svelte
<script lang="ts" module>
	export interface TooltipItem {
		id: number | string;
		name: string;
		designation: string;
		image: string;
	}

	export interface AnimatedTooltipProps {
		/** Array of items to display */
		items: TooltipItem[];
		/** Additional CSS classes for the container */
		class?: string;
		/**
		 * Tint of the presence ring and the light sweep under the name. Any CSS
		 * colour (`"#f5a97f"`, `"oklch(0.7 0.14 160)"`, `"var(--primary)"`).
		 * Leave unset for the default soft iridescent pair, which adapts to the
		 * light and dark themes.
		 */
		accent?: string;
		/** Avatar diameter in pixels. */
		size?: number;
	}
</script>

<script lang="ts">
	import { cn } from "$lib/utils.js";
	import { createReducedMotion } from "../_internals/motion/media-query.svelte.js";

	let { items, class: className, accent, size = 56 }: AnimatedTooltipProps = $props();

	const reduced = createReducedMotion();
	$effect(() => reduced.start());

	let hoveredId = $state<number | string | null>(null);
	let mouseX = $state(0);

	/** Index of the active item, or -1 when nothing is hovered/focused. */
	let activeIndex = $derived(
		hoveredId === null ? -1 : items.findIndex((item) => item.id === hoveredId)
	);

	// Pointer offset from the avatar centre, normalised to [-1, 1]. The card
	// leans and slides toward the pointer; reduced motion keeps it upright.
	let lean = $derived(reduced.current ? 0 : Math.max(-1, Math.min(1, mouseX / (size / 2))));
	let rotation = $derived(lean * 7);
	let translation = $derived(lean * 14);

	/** How far item `i` steps aside to make room for the active one. */
	function partOffset(i: number): number {
		if (activeIndex < 0 || reduced.current) return 0;
		const d = i - activeIndex;
		const distance = Math.abs(d);
		if (distance === 1) return Math.sign(d) * 6;
		if (distance === 2) return Math.sign(d) * 2;
		return 0;
	}

	let ringStyle = $derived(
		accent
			? `--at-accent: ${accent}; --at-accent-2: color-mix(in oklab, ${accent} 62%, white);`
			: ""
	);

	function handleMouseEnter(event: MouseEvent, itemId: number | string) {
		// Reset mouseX first to prevent offset from previous item
		const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
		mouseX = event.clientX - rect.left - rect.width / 2;
		hoveredId = itemId;
	}

	function handleMouseMove(event: MouseEvent) {
		if (hoveredId === null) return;
		const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
		mouseX = event.clientX - rect.left - rect.width / 2;
	}

	function handleMouseLeave() {
		hoveredId = null;
		mouseX = 0;
	}

	function handleFocusIn(itemId: number | string) {
		mouseX = 0;
		hoveredId = itemId;
	}

	function handleFocusOut() {
		hoveredId = null;
		mouseX = 0;
	}

	function tooltipId(itemId: number | string) {
		return `animated-tooltip-${itemId}`;
	}

	/** Exit: a short settle downward (opacity only under reduced motion). */
	function sink(_node: Element) {
		const still = reduced.current;
		return {
			duration: still ? 120 : 160,
			easing: (t: number) => t * t,
			css: (t: number) =>
				still
					? `opacity: ${t};`
					: `opacity: ${t}; transform: translateY(${(1 - t) * 4}px) scale(${0.97 + 0.03 * t});`,
		};
	}
</script>

<div
	class={cn("at-root flex flex-row items-center", className)}
	style="--_at-size: {size}px; {ringStyle}"
>
	{#each items as item, i (item.id)}
		{@const active = hoveredId === item.id}
		{@const shift = partOffset(i)}
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
		<div
			class={cn("at-item group relative", active && "at-active", shift !== 0 && "at-parted")}
			style="--_at-shift: {shift}px;"
			data-active={active ? "" : undefined}
			data-part={shift < 0 ? "before" : shift > 0 ? "after" : undefined}
			onmouseenter={(e) => handleMouseEnter(e, item.id)}
			onmouseleave={handleMouseLeave}
			onmousemove={handleMouseMove}
			onfocusin={() => handleFocusIn(item.id)}
			onfocusout={handleFocusOut}
			tabindex="0"
			aria-describedby={active ? tooltipId(item.id) : undefined}
		>
			<!-- Tooltip -->
			{#if active}
				<div
					id={tooltipId(item.id)}
					role="tooltip"
					class="at-tip pointer-events-none absolute left-1/2 z-50"
					style="transform: translateX(calc(-50% + {translation}px)) rotate({rotation}deg);"
				>
					<div class="at-card" out:sink>
						<span class="at-pointer" aria-hidden="true"></span>
						<div class="at-name">{item.name}</div>
						<span class="at-rule" aria-hidden="true"><span class="at-glint"></span></span>
						<div class="at-role">{item.designation}</div>
					</div>
				</div>
			{/if}

			<!-- Avatar: presence ring + photo -->
			<div class={cn("at-avatar", active && !reduced.current && "at-lifted")}>
				<span class="at-glow" aria-hidden="true"></span>
				<span class="at-disc" aria-hidden="true"></span>
				<span class="at-ring" aria-hidden="true"></span>
				<img
					src={item.image}
					alt={item.name}
					class="at-img relative !m-0 rounded-full object-cover object-top !p-0"
				/>
			</div>
		</div>
	{/each}
</div>

<style>
	@property --at-angle {
		syntax: "<angle>";
		inherits: false;
		initial-value: 0deg;
	}

	.at-root {
		/* Public, class-themeable knobs with private fallbacks. */
		--_at-a: var(--at-accent, oklch(0.62 0.13 295));
		--_at-b: var(--at-accent-2, oklch(0.7 0.1 220));
		--_at-core: color-mix(in oklab, var(--_at-a) 45%, white);
		--_at-sep: var(--at-separator, var(--background, #ffffff));
		--_at-ease-out: cubic-bezier(0.16, 1, 0.3, 1);
		--_at-ease-rise: cubic-bezier(0.34, 1.32, 0.64, 1);
		--_at-ease-inout: cubic-bezier(0.4, 0, 0.2, 1);
		--_at-card-bg: rgba(255, 255, 255, 0.85);
		--_at-card-line: rgba(0, 0, 0, 0.08);
		--_at-card-hi: rgba(255, 255, 255, 0.9);
		--_at-card-shadow: 0 10px 28px -12px rgba(0, 0, 0, 0.28), 0 2px 6px -2px rgba(0, 0, 0, 0.1);
		--_at-name: #111113;
		--_at-role: rgba(0, 0, 0, 0.55);
	}

	:global(.dark) .at-root {
		--_at-a: var(--at-accent, oklch(0.78 0.1 295));
		--_at-b: var(--at-accent-2, oklch(0.83 0.08 210));
		--_at-card-bg: rgba(20, 20, 22, 0.85);
		--_at-card-line: rgba(255, 255, 255, 0.1);
		--_at-card-hi: rgba(255, 255, 255, 0.06);
		--_at-card-shadow: 0 14px 32px -12px rgba(0, 0, 0, 0.8), 0 2px 6px -2px rgba(0, 0, 0, 0.5);
		--_at-name: #f4f4f5;
		--_at-role: rgba(255, 255, 255, 0.55);
	}

	/* ---------- stack ---------- */

	.at-item {
		outline: none;
		transform: translateX(var(--_at-shift, 0px));
	}

	.at-item:not(:last-child) {
		margin-inline-end: calc(var(--_at-size) * -0.285);
	}

	.at-item.at-active {
		z-index: 30;
	}

	.at-avatar {
		position: relative;
		width: var(--_at-size);
		height: var(--_at-size);
		border-radius: 9999px;
		isolation: isolate;
		transform-origin: 50% 60%;
	}

	/* The hairline that separates stacked avatars, in the page colour. */
	.at-disc {
		position: absolute;
		inset: 0;
		z-index: 1;
		border-radius: 9999px;
		background: var(--_at-sep);
		box-shadow: 0 0 0 2px var(--_at-sep);
	}

	.at-avatar.at-lifted {
		transform: translateY(-4px) scale(1.08);
	}

	.at-img {
		position: absolute;
		inset: 3px;
		width: calc(100% - 6px);
		height: calc(100% - 6px);
		z-index: 3;
	}

	/* The lit ring is the focus indicator; forced-colors mode strips it, so
	   fall back to a system-coloured outline there. */
	@media (forced-colors: active) {
		.at-item:focus-visible .at-avatar {
			outline: 2px solid Highlight;
			outline-offset: 2px;
		}
	}

	/* ---------- presence ring ---------- */

	.at-ring,
	.at-glow {
		position: absolute;
		border-radius: 9999px;
		background: conic-gradient(
			from var(--at-angle),
			var(--_at-a) 0deg,
			var(--_at-b) 150deg,
			var(--_at-core) 205deg,
			var(--_at-a) 260deg,
			var(--_at-a) 360deg
		);
	}

	.at-ring {
		inset: 0;
		z-index: 2;
		padding: 2px;
		-webkit-mask:
			linear-gradient(#000 0 0) content-box,
			linear-gradient(#000 0 0);
		-webkit-mask-composite: xor;
		mask:
			linear-gradient(#000 0 0) content-box exclude,
			linear-gradient(#000 0 0);
		opacity: 0.35;
		transition: opacity 300ms var(--_at-ease-inout);
	}

	.at-glow {
		inset: -3px;
		z-index: 0;
		filter: blur(7px);
		opacity: 0;
		transition: opacity 300ms var(--_at-ease-inout);
	}

	.at-active .at-ring {
		opacity: 1;
	}

	.at-active .at-glow {
		opacity: 0.55;
	}

	/* ---------- glass card ---------- */

	.at-tip {
		bottom: calc(100% + 12px);
		transform-origin: 50% 100%;
	}

	.at-card {
		position: relative;
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 5px;
		padding: 8px 14px 9px;
		border-radius: 10px;
		white-space: nowrap;
		background: var(--_at-card-bg);
		border: 1px solid var(--_at-card-line);
		box-shadow:
			inset 0 1px 0 var(--_at-card-hi),
			var(--_at-card-shadow);
		-webkit-backdrop-filter: blur(12px) saturate(1.4);
		backdrop-filter: blur(12px) saturate(1.4);
		transform-origin: 50% 100%;
		animation: at-fade 160ms var(--_at-ease-out) both;
	}

	.at-pointer {
		position: absolute;
		left: 50%;
		bottom: -5px;
		width: 9px;
		height: 9px;
		margin-left: -4.5px;
		background: var(--_at-card-bg);
		border-right: 1px solid var(--_at-card-line);
		border-bottom: 1px solid var(--_at-card-line);
		border-bottom-right-radius: 2px;
		transform: rotate(45deg);
		clip-path: polygon(100% 0, 100% 100%, 0 100%);
		-webkit-backdrop-filter: blur(12px);
		backdrop-filter: blur(12px);
	}

	.at-name {
		font-size: 0.8125rem;
		line-height: 1.1rem;
		font-weight: 600;
		letter-spacing: -0.005em;
		color: var(--_at-name);
	}

	.at-role {
		font-size: 0.6875rem;
		line-height: 0.9rem;
		color: var(--_at-role);
	}

	/* One thin line of light under the name: a faint resting hairline plus a
	   glint that sweeps across it once when the card opens. */
	.at-rule {
		position: relative;
		display: block;
		width: 100%;
		min-width: 64px;
		height: 7px;
		margin: -3px 0;
		overflow: clip;
		background: linear-gradient(
				90deg,
				transparent,
				color-mix(in oklab, var(--_at-a) 50%, transparent) 30%,
				color-mix(in oklab, var(--_at-b) 50%, transparent) 70%,
				transparent
			)
			center / 100% 1px no-repeat;
	}

	.at-glint {
		display: none;
	}

	@media (prefers-reduced-motion: no-preference) {
		.at-item {
			transition: transform 380ms var(--_at-ease-out);
		}

		.at-avatar {
			transition: transform 420ms var(--_at-ease-out);
		}

		.at-ring,
		.at-glow {
			transition:
				opacity 300ms var(--_at-ease-inout),
				--at-angle 900ms var(--_at-ease-out);
		}

		.at-active .at-ring,
		.at-active .at-glow {
			--at-angle: 140deg;
		}

		.at-tip {
			transition: transform 240ms var(--_at-ease-out);
		}

		.at-card {
			animation: at-rise 260ms var(--_at-ease-rise) both;
		}

		.at-glint {
			display: block;
			position: absolute;
			top: 3px;
			left: 0;
			width: 60%;
			height: 1px;
			border-radius: 1px;
			background: linear-gradient(
				90deg,
				transparent,
				var(--_at-a) 25%,
				var(--_at-core) 50%,
				var(--_at-b) 75%,
				transparent
			);
			/* Soft halo so a 1px line still reads as light. */
			filter: drop-shadow(0 0 2px var(--_at-a)) drop-shadow(0 0 4px var(--_at-b));
			transform: translateX(-110%);
			animation: at-sweep 760ms var(--_at-ease-inout) 90ms both;
		}
	}

	@keyframes at-rise {
		from {
			opacity: 0;
			transform: translateY(6px) scale(0.94);
		}
		to {
			opacity: 1;
			transform: none;
		}
	}

	@keyframes at-fade {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	@keyframes at-sweep {
		from {
			transform: translateX(-110%);
		}
		to {
			transform: translateX(180%);
		}
	}
</style>
