// react/src/internals/markdown/Markdown.tsx
/*
 * The two renderer components sit one directory below the parser they consume,
 * and that nesting is load-bearing.
 *
 * `Markdown.tsx` and `markdown.ts` differ only in case. Emitted side by side
 * into one flat output directory they are the same path on a case-insensitive
 * filesystem (macOS, Windows), and the declaration build — `tsc -p
 * tsconfig.build.json`, which compiles all of `src`, not just the entry graph —
 * wrote a single `dist/internals/markdown.d.ts` holding the parser's types with
 * this module's `Markdown` / `MarkdownProps` silently gone. The bundle half
 * (`preserveModules`, `entryFileNames: "[name].js"`) would collide the same way
 * the moment a component imported this file.
 *
 * Nesting keeps the two emitted paths distinct; the file names themselves are
 * unchanged, and `../markdown.js` names the parser unambiguously from here.
 */
import { Fragment, type ReactNode } from "react";
import { cn } from "../../utils.js";
import { parseMarkdown, type BlockToken } from "../markdown.js";
import { MarkdownInline } from "./MarkdownInline.js";
import "./markdown.css";

export interface MarkdownProps {
	/** Markdown source. Safe to update on every streamed chunk. */
	text?: string;
	className?: string;
	/**
	 * Already-parsed blocks, used when the component renders itself for a
	 * blockquote. Consumers pass `text`.
	 */
	blocks?: BlockToken[];
	/**
	 * Rendered inline at the very end of the document — a streaming caret, say.
	 * Every block here is block-level, so a caret placed after the component
	 * would sit on its own line instead of trailing the last character; this
	 * puts it inside the last paragraph, heading or list item instead. A
	 * document ending in code, a table, a rule, or nothing at all has no inline
	 * tail to hold it, and drops it.
	 */
	trailingCursor?: ReactNode;
}

/**
 * One block token. `cursor` is only ever passed for the last block of the
 * document; every other block receives `undefined` and renders no tail.
 */
function renderBlock(block: BlockToken, cursor: ReactNode): ReactNode {
	switch (block.type) {
		case "paragraph":
			return (
				<p className="ft-md-p">
					<MarkdownInline tokens={block.children} />
					{cursor}
				</p>
			);
		case "heading": {
			const Heading = `h${block.depth}` as const;
			return (
				<Heading className="ft-md-h" data-depth={block.depth}>
					<MarkdownInline tokens={block.children} />
					{cursor}
				</Heading>
			);
		}
		case "code":
			return (
				<pre className="ft-md-pre" data-lang={block.lang || undefined}>
					<code>{block.text}</code>
				</pre>
			);
		case "list": {
			const items = block.items.map((item, itemIndex) => (
				<li key={itemIndex}>
					<MarkdownInline tokens={item} />
					{itemIndex === block.items.length - 1 ? cursor : undefined}
				</li>
			));
			return block.ordered ? (
				<ol className="ft-md-ol" start={block.start}>
					{items}
				</ol>
			) : (
				<ul className="ft-md-ul">{items}</ul>
			);
		}
		case "blockquote":
			return (
				<blockquote className="ft-md-quote">
					<Markdown blocks={block.children} trailingCursor={cursor} />
				</blockquote>
			);
		case "table":
			return (
				<div className="ft-md-table-scroll">
					<table className="ft-md-table">
						<thead>
							<tr>
								{block.header.map((cell, i) => (
									<th key={i} style={{ textAlign: block.align[i] ?? undefined }}>
										<MarkdownInline tokens={cell} />
									</th>
								))}
							</tr>
						</thead>
						<tbody>
							{block.rows.map((row, rowIndex) => (
								<tr key={rowIndex}>
									{row.map((cell, i) => (
										<td key={i} style={{ textAlign: block.align[i] ?? undefined }}>
											<MarkdownInline tokens={cell} />
										</td>
									))}
								</tr>
							))}
						</tbody>
					</table>
				</div>
			);
		case "hr":
			return <hr className="ft-md-hr" />;
	}
}

export function Markdown({ text = "", className, blocks, trailingCursor }: MarkdownProps) {
	const nodes = blocks ?? parseMarkdown(text);
	const lastIndex = nodes.length - 1;

	return (
		<div className={cn("ft-md", className)}>
			{nodes.map((block, index) => (
				// Blocks have no identity beyond their position; a streamed document
				// is re-parsed and re-rendered whole on every chunk.
				<Fragment key={index}>
					{renderBlock(block, index === lastIndex ? trailingCursor : undefined)}
				</Fragment>
			))}
		</div>
	);
}

// vue/src/internals/Markdown.vue
<script lang="ts">
import type { HTMLAttributes } from "vue";
import type { BlockToken } from "./markdown.js";

export interface MarkdownProps {
	/** Markdown source. Safe to update on every streamed chunk. */
	text?: string;
	class?: HTMLAttributes["class"];
	/**
	 * Already-parsed blocks, used when the component renders itself for a
	 * blockquote. Consumers pass `text`.
	 */
	blocks?: BlockToken[];
}
</script>

<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils.js";
import { parseMarkdown } from "./markdown.js";
import MarkdownInline from "./MarkdownInline.vue";
import "./markdown.css";

defineOptions({ name: "Markdown", inheritAttrs: false });

const { text = "", class: className, blocks } = defineProps<MarkdownProps>();
/**
 * Rendered inline at the very end of the document — a streaming caret, say.
 * Every block here is block-level, so a caret placed after the component
 * would sit on its own line instead of trailing the last character; this
 * slot lands inside the last paragraph, heading or list item instead. A
 * document ending in code, a table, a rule, or nothing at all has no inline
 * tail to hold it, and drops it.
 */
defineSlots<{ trailingCursor?: () => unknown }>();

const nodes = computed(() => blocks ?? parseMarkdown(text));
const lastIndex = computed(() => nodes.value.length - 1);
</script>

<template>
	<div :class="cn('ft-md', className)">
		<template v-for="(block, index) in nodes" :key="index">
			<p v-if="block.type === 'paragraph'" class="ft-md-p">
				<MarkdownInline :tokens="block.children" /><slot
					v-if="index === lastIndex"
					name="trailingCursor"
				/>
			</p>
			<component
				:is="`h${block.depth}`"
				v-else-if="block.type === 'heading'"
				class="ft-md-h"
				:data-depth="block.depth"
			>
				<MarkdownInline :tokens="block.children" /><slot
					v-if="index === lastIndex"
					name="trailingCursor"
				/>
			</component>
			<pre v-else-if="block.type === 'code'" class="ft-md-pre" :data-lang="block.lang || null"><code>{{ block.text }}</code></pre>
			<ol v-else-if="block.type === 'list' && block.ordered" class="ft-md-ol" :start="block.start">
				<li v-for="(item, itemIndex) in block.items" :key="itemIndex">
					<MarkdownInline :tokens="item" /><slot
						v-if="index === lastIndex && itemIndex === block.items.length - 1"
						name="trailingCursor"
					/>
				</li>
			</ol>
			<ul v-else-if="block.type === 'list'" class="ft-md-ul">
				<li v-for="(item, itemIndex) in block.items" :key="itemIndex">
					<MarkdownInline :tokens="item" /><slot
						v-if="index === lastIndex && itemIndex === block.items.length - 1"
						name="trailingCursor"
					/>
				</li>
			</ul>
			<blockquote v-else-if="block.type === 'blockquote'" class="ft-md-quote">
				<Markdown :blocks="block.children">
					<template v-if="index === lastIndex" #trailingCursor
						><slot name="trailingCursor"
					/></template>
				</Markdown>
			</blockquote>
			<div v-else-if="block.type === 'table'" class="ft-md-table-scroll">
				<table class="ft-md-table">
					<thead>
						<tr>
							<th
								v-for="(cell, i) in block.header"
								:key="i"
								:style="{ textAlign: block.align[i] ?? undefined }"
							>
								<MarkdownInline :tokens="cell" />
							</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="(row, rowIndex) in block.rows" :key="rowIndex">
							<td
								v-for="(cell, i) in row"
								:key="i"
								:style="{ textAlign: block.align[i] ?? undefined }"
							>
								<MarkdownInline :tokens="cell" />
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<hr v-else-if="block.type === 'hr'" class="ft-md-hr" />
		</template>
	</div>
</template>
