// src/lib/portfolio/sections/About.svelte
<section id="about" class="py-20 px-6">
	<div class="max-w-4xl mx-auto">
		<div class="text-center mb-16">
			<h2 class="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-foreground mb-4">
				About
			</h2>
		</div>

		<div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
			<div class="space-y-6">
				<p class="text-lg sm:text-xl text-muted-foreground leading-relaxed">
					I'm a Front-End & UI Engineer at
					<a
						href="https://www.ansys.com"
						target="_blank"
						rel="noopener noreferrer"
						class="font-semibold text-foreground underline-offset-4 hover:underline"
						aria-label="Open Ansys website in a new tab"
					>
						Ansys&reg;
					</a>
					<span class="text-foreground/80"> (part of </span>
					<span class="text-foreground/90 text-[0.9em] align-baseline">Synopsys Inc.)</span>,
					with a creative foundation from
					<span class="font-semibold text-foreground"
						>Gobelins Paris &mdash; l'&Eacute;cole de l'Image</span
					>.
				</p>

				<p class="text-lg sm:text-xl text-muted-foreground leading-relaxed">
					I build intuitive, high-performance UIs for Ansys Digital Safety Manager, helping safety
					engineers streamline planning, execution and monitoring of safety cases.
				</p>

				<p class="text-lg sm:text-xl text-muted-foreground leading-relaxed">
					My approach bridges technical precision and creative design, with a strong focus on clean
					architecture, performance optimization and user-centered experiences.
				</p>
			</div>

			<div class="flex justify-center lg:justify-end">
				<div
					class="w-80 h-96 border-2 border-dashed border-muted-foreground/20 rounded-lg overflow-hidden shadow-lg"
				>
					<img
						src="/portfolio/IMG_0318.jpg"
						alt="Rama Herbin in Chicago"
						class="w-full h-full object-cover"
						loading="lazy"
					/>
				</div>
			</div>
		</div>
	</div>
</section>

// examples/react-demo/src/components/sections/About.tsx
import { NumberTicker } from "fancy-ui-react";
import { c, cList } from "@/content/content";

export function About() {
	return (
		<section id="about" className="px-6 py-20">
			<div className="mx-auto max-w-4xl">
				<div className="mb-16 text-center">
					<h2 className="text-foreground mb-4 text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">
						{c("home.about.title")}
					</h2>
				</div>

				<div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-2">
					<div className="space-y-6">
						<p className="text-muted-foreground text-lg leading-relaxed sm:text-xl">
							<span>{c("home.about.intro")}</span>{" "}
							<a
								href={c("home.hero.sibling.href")}
								target="_blank"
								rel="noopener noreferrer"
								className="text-foreground font-semibold underline-offset-4 hover:underline"
								aria-label={`Open ${c("home.hero.sibling.label")} on npm in a new tab`}
							>
								{c("home.hero.sibling.label")}
							</a>
							<span>{c("home.about.sibling-tail")}</span>{" "}
							<code className="text-foreground rounded bg-muted px-1.5 py-0.5 font-mono text-[0.85em]">
								{c("home.about.subpath")}
							</code>{" "}
							<span>{c("home.about.subpath-tail")}</span>
						</p>

						<p className="text-muted-foreground text-lg leading-relaxed sm:text-xl">{c("home.about.paragraph-2")}</p>

						<p className="text-muted-foreground text-lg leading-relaxed sm:text-xl">{c("home.about.paragraph-3")}</p>
					</div>

					{/* The portrait slot becomes a spec card: the component count ticks up
					    when it scrolls into view. */}
					<div className="flex justify-center lg:justify-end">
						<div className="border-muted-foreground/20 bg-surface-raised flex h-96 w-80 flex-col justify-between overflow-hidden rounded-lg border-2 border-dashed p-8 shadow-lg">
							<div>
								<NumberTicker value={144} className="text-foreground text-7xl font-bold tracking-tight" />
								<p className="text-muted-foreground mt-1 font-mono text-xs tracking-[0.14em] uppercase">
									{c("home.about.card.label")}
								</p>
							</div>
							<ul className="text-muted-foreground space-y-2 text-sm">
								{cList("home.about.card.items").map((item) => (
									<li key={item} className="flex items-center gap-2">
										<span className="bg-accent-work h-1.5 w-1.5 rounded-full" aria-hidden="true" />
										{item}
									</li>
								))}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
