// vue/src/components/focus/Focus.vue
<script lang="ts">
import type { HTMLAttributes } from "vue";

export interface FocusProps {
	/** Sentence to split into words */
	sentence?: string;
	/** Follow the hovered word instead of auto-cycling */
	manualMode?: boolean;
	/** Blur applied to out-of-focus words, in px */
	blurAmount?: number;
	/** Color of the focus frame corners */
	borderColor?: string;
	/** Focus transition duration in seconds */
	animationDuration?: number;
	/** Pause between auto-cycle steps in seconds */
	pauseBetweenAnimations?: number;
	/** Additional CSS classes */
	class?: HTMLAttributes["class"];
}
</script>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, useTemplateRef, watch } from "vue";
import { cn } from "../../utils.js";

defineOptions({ name: "Focus", inheritAttrs: false });

const {
	sentence = "Fancy Focus",
	manualMode = false,
	blurAmount = 5,
	borderColor = "green",
	animationDuration = 0.5,
	pauseBetweenAnimations = 1,
	class: className = "",
} = defineProps<FocusProps>();

const words = computed(() => sentence.split(" "));
const containerRef = useTemplateRef<HTMLDivElement>("containerRef");
// Plain array sink, mirroring the Svelte `$state([])` word-element list: it is
// only read imperatively from `updateFocusRect`, never rendered from.
const wordElements = ref<(HTMLSpanElement | null)[]>([]);
const currentIndex = ref(0);
const focusRect = ref({ x: 0, y: 0, width: 0, height: 0 });

function setWordRef(el: Element | null, index: number) {
	wordElements.value[index] = el as HTMLSpanElement | null;
}

function updateFocusRect() {
	const wordEl = wordElements.value[currentIndex.value];
	const container = containerRef.value;
	if (!wordEl || !container) return;
	const parentRect = container.getBoundingClientRect();
	const wordRect = wordEl.getBoundingClientRect();
	focusRect.value = {
		x: wordRect.left - parentRect.left,
		y: wordRect.top - parentRect.top,
		width: wordRect.width,
		height: wordRect.height,
	};
}

function handleMouseEnter(index: number) {
	if (manualMode) {
		currentIndex.value = index;
	}
}

function handleMouseLeave() {
	if (manualMode) {
		currentIndex.value = 0;
	}
}

// Mirrors the Svelte `$effect(() => { currentIndex; tick().then(updateFocusRect); })`:
// tracks currentIndex only, measures on the next tick.
watch(
	currentIndex,
	() => {
		nextTick().then(updateFocusRect);
	},
	{ flush: "post" },
);

let intervalId: ReturnType<typeof setInterval> | undefined;

onMounted(() => {
	updateFocusRect();

	if (!manualMode) {
		// Timing props are read once here, as the Svelte `onMount` closure
		// captures them once: a later prop change does not restart the cycle.
		const intervalMs = animationDuration * 1000 + pauseBetweenAnimations * 1000;
		intervalId = setInterval(() => {
			currentIndex.value = (currentIndex.value + 1) % words.value.length;
		}, intervalMs);
	}
});

onBeforeUnmount(() => {
	if (intervalId !== undefined) clearInterval(intervalId);
});
</script>

<template>
	<div ref="containerRef" :class="cn('focus-container', className)">
		<span
			v-for="(word, index) in words"
			:key="index"
			:ref="(el) => setWordRef(el as Element | null, index)"
			class="focus-word"
			:class="{ manual: manualMode, active: index === currentIndex && !manualMode }"
			:style="{
				filter: index === currentIndex ? 'blur(0px)' : `blur(${blurAmount}px)`,
				transition: `filter ${animationDuration}s ease`,
				'--border-color': borderColor,
			}"
			@mouseenter="handleMouseEnter(index)"
			@mouseleave="handleMouseLeave"
		>
			{{ word }}
		</span>

		<div
			class="focus-frame"
			:style="{
				transform: `translate(${focusRect.x}px, ${focusRect.y}px)`,
				width: `${focusRect.width}px`,
				height: `${focusRect.height}px`,
				opacity: currentIndex >= 0 ? 1 : 0,
				transition: `all ${animationDuration}s ease`,
				'--border-color': borderColor,
			}"
		>
			<span class="corner top-left"></span>
			<span class="corner top-right"></span>
			<span class="corner bottom-left"></span>
			<span class="corner bottom-right"></span>
		</div>
	</div>
</template>

<style scoped>
.focus-container {
	position: relative;
	display: flex;
	gap: 1em;
	justify-content: center;
	align-items: center;
	flex-wrap: wrap;
}

.focus-word {
	position: relative;
	font-size: 3rem;
	font-weight: 900;
	cursor: pointer;
	transition:
		filter 0.3s ease,
		color 0.3s ease;
}

.focus-word.active {
	filter: blur(0);
}

.focus-frame {
	position: absolute;
	top: 0;
	left: 0;
	pointer-events: none;
	box-sizing: content-box;
	border: none;
}

.corner {
	position: absolute;
	width: 1rem;
	height: 1rem;
	border: 3px solid var(--border-color, #fff);
	filter: drop-shadow(0px 0px 4px var(--border-color, #fff));
	border-radius: 3px;
	transition: none;
}

.top-left {
	top: -10px;
	left: -10px;
	border-right: none;
	border-bottom: none;
}

.top-right {
	top: -10px;
	right: -10px;
	border-left: none;
	border-bottom: none;
}

.bottom-left {
	bottom: -10px;
	left: -10px;
	border-right: none;
	border-top: none;
}

.bottom-right {
	bottom: -10px;
	right: -10px;
	border-left: none;
	border-top: none;
}
</style>

// react/src/components/focus/Focus.tsx
import { useEffect, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { cn } from "../../utils.js";
import { useLiveRef } from "../../internals/dom/use-live-ref.js";
import "./focus.css";

/**
 * Focus - Sentence with a roving focus frame
 *
 * Splits a sentence into words, blurs all but the current one, and moves a
 * cornered frame over the word in focus. Cycles automatically on an interval,
 * or follows the hovered word in manual mode.
 */
export interface FocusProps {
	/** Sentence to split into words */
	sentence?: string;
	/** Follow the hovered word instead of auto-cycling */
	manualMode?: boolean;
	/** Blur applied to out-of-focus words, in px */
	blurAmount?: number;
	/** Color of the focus frame corners */
	borderColor?: string;
	/** Focus transition duration in seconds */
	animationDuration?: number;
	/** Pause between auto-cycle steps in seconds */
	pauseBetweenAnimations?: number;
	/** Additional CSS classes */
	className?: string;
}

export function Focus({
	sentence = "Fancy Focus",
	manualMode = false,
	blurAmount = 5,
	borderColor = "green",
	animationDuration = 0.5,
	pauseBetweenAnimations = 1,
	className = "",
}: FocusProps) {
	const words = sentence.split(" ");
	const containerRef = useRef<HTMLDivElement | null>(null);
	const wordElements = useRef<(HTMLSpanElement | null)[]>([]);
	const [currentIndex, setCurrentIndex] = useState(0);
	const [focusRect, setFocusRect] = useState({ x: 0, y: 0, width: 0, height: 0 });

	// The interval callback reads the live word count, as the Svelte closure
	// does over its derived value, without restarting the interval.
	const wordCount = useLiveRef(words.length);

	function handleMouseEnter(index: number) {
		if (manualMode) {
			setCurrentIndex(index);
		}
	}

	function handleMouseLeave() {
		if (manualMode) {
			setCurrentIndex(0);
		}
	}

	// Runs after commit, the counterpart of `$effect` + `tick()`: measures the
	// current word once the DOM reflects `currentIndex`. Covers mount too.
	useEffect(() => {
		const wordEl = wordElements.current[currentIndex];
		const container = containerRef.current;
		if (!wordEl || !container) return;
		const parentRect = container.getBoundingClientRect();
		const wordRect = wordEl.getBoundingClientRect();
		setFocusRect({
			x: wordRect.left - parentRect.left,
			y: wordRect.top - parentRect.top,
			width: wordRect.width,
			height: wordRect.height,
		});
	}, [currentIndex]);

	// Mount-only, as the Svelte side starts its interval in onMount: the timing
	// props are captured once and a later change does not restart the cycle.
	const startupRef = useLiveRef({ manualMode, animationDuration, pauseBetweenAnimations });
	useEffect(() => {
		const { manualMode, animationDuration, pauseBetweenAnimations } = startupRef.current;
		if (manualMode) return;
		const intervalMs = animationDuration * 1000 + pauseBetweenAnimations * 1000;
		const id = setInterval(() => {
			setCurrentIndex((index) => (index + 1) % wordCount.current);
		}, intervalMs);
		return () => clearInterval(id);
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	return (
		<div ref={containerRef} className={cn("focus-container", className)}>
			{words.map((word, index) => (
				<span
					key={index}
					ref={(node) => {
						wordElements.current[index] = node;
					}}
					className={cn(
						"focus-word",
						manualMode && "manual",
						index === currentIndex && !manualMode && "active",
					)}
					style={
						{
							filter: index === currentIndex ? "blur(0px)" : `blur(${blurAmount}px)`,
							transition: `filter ${animationDuration}s ease`,
							"--border-color": borderColor,
						} as CSSProperties
					}
					onMouseEnter={() => handleMouseEnter(index)}
					onMouseLeave={handleMouseLeave}
				>
					{word}
				</span>
			))}

			<div
				className="focus-frame"
				style={
					{
						transform: `translate(${focusRect.x}px, ${focusRect.y}px)`,
						width: `${focusRect.width}px`,
						height: `${focusRect.height}px`,
						opacity: currentIndex >= 0 ? 1 : 0,
						transition: `all ${animationDuration}s ease`,
						"--border-color": borderColor,
					} as CSSProperties
				}
			>
				<span className="corner top-left"></span>
				<span className="corner top-right"></span>
				<span className="corner bottom-left"></span>
				<span className="corner bottom-right"></span>
			</div>
		</div>
	);
}
