// src/lib/fancy-ui/sidebar/SidebarFooter.svelte
<script lang="ts" module>
	import type { Snippet } from "svelte";

	export interface SidebarFooterProps {
		/** A decorative avatar, shown even when the sidebar is collapsed. */
		avatar?: Snippet;
		/** The name / text next to the avatar. Moves to `sr-only` while collapsed — never removed. */
		children?: Snippet;
		/** Additional CSS classes */
		class?: string;
		/** Element reference */
		ref?: HTMLDivElement | null;
	}
</script>

<script lang="ts">
	import { getContext } from "svelte";
	import { cn } from "$lib/utils.js";
	import SidebarSeparator from "./SidebarSeparator.svelte";
	import { SIDEBAR_KEY, type SidebarContext } from "./types.js";

	let { avatar, children, class: className, ref = $bindable(null) }: SidebarFooterProps = $props();

	const sidebar = getContext<SidebarContext | undefined>(SIDEBAR_KEY);
	const collapsed = $derived(sidebar?.collapsed ?? false);
</script>

<div bind:this={ref} class={cn("ft-sidebar-footer mt-auto flex w-full flex-col", className)}>
	<SidebarSeparator />
	<div
		class={cn(
			"flex items-center gap-2.5 px-2 py-[7px] text-[12px]",
			"text-muted-foreground",
			collapsed && "justify-center"
		)}
	>
		{#if avatar}
			<span class="shrink-0" aria-hidden="true">
				{@render avatar()}
			</span>
		{/if}
		<span class={cn("min-w-0 truncate", collapsed && "sr-only")}>
			{@render children?.()}
		</span>
	</div>
</div>

// react/src/components/sidebar/SidebarFooter.tsx
import { forwardRef, useContext } from "react";
import type { ReactNode } from "react";

import { cn } from "../../utils.js";
import { SidebarSeparator } from "./SidebarSeparator.js";
import { SIDEBAR_KEY } from "./types.js";

export interface SidebarFooterProps {
	/** A decorative avatar, shown even when the sidebar is collapsed. */
	avatar?: ReactNode;
	/** The name / text next to the avatar. Moves to `sr-only` while collapsed — never removed. */
	children?: ReactNode;
	/** Additional CSS classes */
	className?: string;
}

export const SidebarFooter = forwardRef<HTMLDivElement, SidebarFooterProps>(function SidebarFooter(
	{ avatar, children, className },
	ref
) {
	const sidebar = useContext(SIDEBAR_KEY);
	const collapsed = sidebar?.collapsed ?? false;

	return (
		<div ref={ref} className={cn("ft-sidebar-footer mt-auto flex w-full flex-col", className)}>
			<SidebarSeparator />
			<div
				className={cn(
					"flex items-center gap-2.5 px-2 py-[7px] text-[12px]",
					"text-muted-foreground",
					collapsed && "justify-center"
				)}
			>
				{avatar ? (
					<span className="shrink-0" aria-hidden="true">
						{avatar}
					</span>
				) : null}
				<span className={cn("min-w-0 truncate", collapsed && "sr-only")}>{children}</span>
			</div>
		</div>
	);
});

SidebarFooter.displayName = "SidebarFooter";
