// src/lib/fancy-ui/reasoning-panel/ReasoningPanel.svelte
<script lang="ts" module>
	/**
	 * Props for ReasoningPanel
	 */
	export interface ReasoningPanelProps {
		/** The reasoning trace so far. Hand over a longer string to stream more in. */
		text: string;
		/** Whether the trace is still growing. Drives the timer, the shimmer, and autoscroll. */
		streaming?: boolean;
		/**
		 * Whether the trace is expanded. Bindable, and left alone until either the
		 * component or the reader changes it — see the open-behaviour contract in
		 * the README.
		 */
		open?: boolean;
		/** Header text. */
		label?: string;
		/** Epoch ms the current burst started at. Pins the live timer's origin. */
		since?: number;
		/** Final duration for the summary line. Falls back to what the timer measured. */
		durationMs?: number;
		/** Scroll height of the trace once expanded. */
		maxHeight?: string;
		/** Called whenever the panel opens or closes, by click or on its own. */
		onToggle?: (open: boolean) => void;
		/** Additional CSS classes */
		class?: string;
		/** The root element */
		ref?: HTMLDivElement | null;
	}
</script>

<script lang="ts">
	import { untrack } from "svelte";
	import { cn } from "$lib/utils.js";
	import StreamText from "../_internals/StreamText.svelte";
	import { autoscroll } from "../_internals/autoscroll.js";
	import { createElapsed, formatElapsed } from "../_internals/elapsed.svelte.js";

	let {
		text,
		streaming = false,
		open = $bindable(),
		label = "Reasoning",
		since,
		durationMs,
		maxHeight = "12rem",
		onToggle,
		class: className,
		ref = $bindable(null),
	}: ReasoningPanelProps = $props();

	/** How long a finished trace stays on screen before folding itself away. */
	const AUTO_COLLAPSE_MS = 600;

	const uid = $props.id();
	const headerId = `${uid}-header`;
	const bodyId = `${uid}-body`;

	// `open` stays undefined until something actually decides: `autoOpen` carries
	// the answer in the meantime, so a consumer that never touches the prop still
	// gets the automatic behaviour and one that binds it still owns the value.
	let autoOpen = $state(false);
	let userToggled = $state(false);
	let measuredMs = $state(0);
	// Plain lets: neither should wake an effect that writes them.
	let wasStreaming = false;
	let collapseTimer: ReturnType<typeof setTimeout> | undefined;
	// The last value `onToggle` was told about. `commit` keeps it in step with
	// its own calls, so the effect below only speaks up for changes that never
	// went through it — a consumer writing straight to a bound variable.
	let lastNotifiedOpen = untrack(() => open ?? autoOpen);

	const elapsed = createElapsed();

	const isOpen = $derived(open ?? autoOpen);
	const duration = $derived(durationMs ?? measuredMs);
	const summary = $derived(
		streaming
			? formatElapsed(elapsed.ms)
			: duration > 0
				? `Thought for ${formatElapsed(duration)}`
				: ""
	);

	function clearCollapseTimer() {
		if (collapseTimer !== undefined) {
			clearTimeout(collapseTimer);
			collapseTimer = undefined;
		}
	}

	function commit(next: boolean) {
		if (untrack(() => open ?? autoOpen) === next) return;
		open = next;
		autoOpen = next;
		lastNotifiedOpen = next;
		onToggle?.(next);
	}

	function toggle() {
		// From here on the reader owns the panel: no more opening or closing on
		// its own behind their back.
		userToggled = true;
		clearCollapseTimer();
		commit(!isOpen);
	}

	// Open on the first chunk, fold away a beat after the last one — until the
	// reader takes over. `userToggled` is read untracked so that taking over does
	// not itself re-run this.
	$effect(() => {
		const active = streaming;
		untrack(() => {
			clearCollapseTimer();
			if (active) {
				wasStreaming = true;
				if (!userToggled) commit(true);
				return;
			}
			if (!wasStreaming) return;
			wasStreaming = false;
			if (userToggled) return;
			collapseTimer = setTimeout(() => {
				collapseTimer = undefined;
				commit(false);
			}, AUTO_COLLAPSE_MS);
		});
		return clearCollapseTimer;
	});

	// A consumer that writes straight to a variable bound with `bind:open` moves
	// the panel without going through `commit`, so nothing above reports it. The
	// README promises every change is announced, whichever side caused it.
	$effect(() => {
		const next = isOpen;
		untrack(() => {
			if (next === lastNotifiedOpen) return;
			lastNotifiedOpen = next;
			onToggle?.(next);
		});
	});

	// The timer only exists while the trace grows; its last reading survives as
	// the summary duration.
	$effect(() => {
		if (!streaming) return;
		elapsed.start(since ?? Date.now());
		return () => {
			measuredMs = untrack(() => elapsed.ms);
			elapsed.stop();
		};
	});
</script>

<div
	bind:this={ref}
	class={cn("border-border bg-card/50 w-full rounded-lg border text-sm", className)}
>
	<button
		type="button"
		id={headerId}
		class="text-muted-foreground hover:text-foreground flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left transition-colors"
		aria-expanded={isOpen}
		aria-controls={bodyId}
		onclick={toggle}
	>
		<svg
			class="ft-chevron size-3.5 shrink-0"
			class:ft-open={isOpen}
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2.5"
			stroke-linecap="round"
			stroke-linejoin="round"
			aria-hidden="true"
		>
			<path d="m9 6 6 6-6 6" />
		</svg>
		<span class="text-foreground font-medium" class:ft-shimmer={streaming}>{label}</span>
		{#if summary}
			<span class="ml-auto text-xs tabular-nums">{summary}</span>
		{/if}
	</button>

	<div class="ft-body" class:ft-open={isOpen}>
		<div class="overflow-hidden">
			<div
				id={bodyId}
				role="group"
				aria-labelledby={headerId}
				inert={!isOpen}
				class="text-muted-foreground overflow-y-auto px-3 pb-3 leading-relaxed"
				style:max-height={maxHeight}
				use:autoscroll={{ enabled: streaming && isOpen, pinOnConnect: true }}
			>
				<StreamText {text} />
			</div>
		</div>
	</div>
</div>

<style>
	/*
	 * 0fr → 1fr on a one-row grid is the only way to transition "auto" height
	 * without measuring anything. The inner wrapper does the clipping.
	 */
	.ft-body {
		display: grid;
		grid-template-rows: 0fr;
	}

	.ft-body.ft-open {
		grid-template-rows: 1fr;
	}

	.ft-chevron.ft-open {
		transform: rotate(90deg);
	}

	/*
	 * Everything that moves lives behind the query, so reduced motion gets the
	 * same three states with nothing to shorten or fall back from.
	 */
	@media (prefers-reduced-motion: no-preference) {
		.ft-body {
			transition: grid-template-rows 260ms cubic-bezier(0.4, 0, 0.2, 1);
		}

		.ft-chevron {
			transition: transform 220ms cubic-bezier(0.4, 0, 0.2, 1);
		}

		.ft-shimmer {
			background-image: linear-gradient(
				100deg,
				currentColor 40%,
				var(--ft-reasoning-shimmer, color-mix(in oklab, currentColor 35%, transparent)) 50%,
				currentColor 60%
			);
			background-size: 250% 100%;
			background-clip: text;
			/* Keep `color` intact: the gradient stops resolve currentColor at this
			   element, so `color: transparent` would blank every stop. Only the glyph
			   fill goes transparent; the clipped gradient supplies the visible text. */
			-webkit-text-fill-color: transparent;
			animation: ft-reasoning-shimmer 1.9s linear infinite;
		}

		@keyframes ft-reasoning-shimmer {
			from {
				background-position: 150% 0;
			}
			to {
				background-position: -50% 0;
			}
		}
	}
</style>

// react/src/components/reasoning-panel/ReasoningPanel.tsx
import { forwardRef, useEffect, useRef, useState } from "react";
import { cn } from "../../utils.js";
import { StreamText } from "../../internals/StreamText.js";
import { useAutoscroll } from "../../internals/use-autoscroll.js";
import { formatElapsed, useElapsed } from "../../internals/use-elapsed.js";
import { useFancyId } from "../../internals/use-id.js";
import { useComposedRefs } from "../../internals/dom/use-composed-refs.js";
import { useElementRef } from "../../internals/dom/use-element-ref.js";
import { useInertAttribute } from "../../internals/dom/use-inert-attribute.js";
import { useEventCallback } from "../../internals/dom/use-event-callback.js";
import "./reasoning-panel.css";

/**
 * Props for ReasoningPanel
 */
export interface ReasoningPanelProps {
	/** The reasoning trace so far. Hand over a longer string to stream more in. */
	text: string;
	/** Whether the trace is still growing. Drives the timer, the shimmer, and autoscroll. */
	streaming?: boolean;
	/**
	 * Whether the trace is expanded. Left alone until either the component or
	 * the reader changes it — see the open-behaviour contract in the README. A
	 * changed prop value is adopted as the new state and announced through
	 * `onToggle`, the counterpart of a consumer writing to the bound variable
	 * on the Svelte side.
	 */
	open?: boolean;
	/** Header text. */
	label?: string;
	/** Epoch ms the current burst started at. Pins the live timer's origin. */
	since?: number;
	/** Final duration for the summary line. Falls back to what the timer measured. */
	durationMs?: number;
	/** Scroll height of the trace once expanded. */
	maxHeight?: string;
	/** Called whenever the panel opens or closes, by click or on its own. */
	onToggle?: (open: boolean) => void;
	/** Additional CSS classes */
	className?: string;
}

/** How long a finished trace stays on screen before folding itself away. */
const AUTO_COLLAPSE_MS = 600;

/**
 * ReasoningPanel
 */
export const ReasoningPanel = forwardRef<HTMLDivElement, ReasoningPanelProps>(
	function ReasoningPanel(
		{
			text,
			streaming = false,
			open: openProp,
			label = "Reasoning",
			since,
			durationMs,
			maxHeight = "12rem",
			onToggle,
			className,
		},
		ref
	) {
		const uid = useFancyId();
		const headerId = `${uid}-header`;
		const bodyId = `${uid}-body`;

		// `open` stays undefined until something actually decides: `autoOpen`
		// carries the answer in the meantime, so a consumer that never touches
		// the prop still gets the automatic behaviour and one that drives it
		// still owns the value.
		const [openState, setOpenState] = useState<boolean | undefined>(openProp);
		const [autoOpen, setAutoOpen] = useState(false);
		const [measuredMs, setMeasuredMs] = useState(0);

		// A changed `open` prop is a consumer decision: adopt it during render,
		// the way a write to the bound variable lands on the Svelte side.
		const lastOpenProp = useRef(openProp);
		if (openProp !== lastOpenProp.current) {
			lastOpenProp.current = openProp;
			if (openProp !== openState) setOpenState(openProp);
		}

		const isOpen = openState ?? autoOpen;

		// Plain refs: none of these should wake an effect that writes them.
		const isOpenRef = useRef(isOpen);
		isOpenRef.current = isOpen;
		const userToggled = useRef(false);
		const wasStreaming = useRef(false);
		const collapseTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
		// The last value `onToggle` was told about. `commit` keeps it in step
		// with its own calls, so the effect below only speaks up for changes
		// that never went through it — a consumer rewriting the `open` prop.
		const lastNotifiedOpen = useRef(isOpen);

		const elapsed = useElapsed();
		const elapsedMsRef = useRef(elapsed.ms);
		elapsedMsRef.current = elapsed.ms;
		const { start: startElapsed, stop: stopElapsed } = elapsed;

		const duration = durationMs ?? measuredMs;
		const summary = streaming
			? formatElapsed(elapsed.ms)
			: duration > 0
				? `Thought for ${formatElapsed(duration)}`
				: "";

		function clearCollapseTimer() {
			if (collapseTimer.current !== undefined) {
				clearTimeout(collapseTimer.current);
				collapseTimer.current = undefined;
			}
		}

		const commit = useEventCallback((next: boolean) => {
			if (isOpenRef.current === next) return;
			isOpenRef.current = next;
			setOpenState(next);
			setAutoOpen(next);
			lastNotifiedOpen.current = next;
			onToggle?.(next);
		});

		function toggle() {
			// From here on the reader owns the panel: no more opening or closing
			// on its own behind their back.
			userToggled.current = true;
			clearCollapseTimer();
			commit(!isOpenRef.current);
		}

		// Open on the first chunk, fold away a beat after the last one — until
		// the reader takes over. `userToggled` is a ref so that taking over
		// does not itself re-run this.
		useEffect(() => {
			clearCollapseTimer();
			if (streaming) {
				wasStreaming.current = true;
				if (!userToggled.current) commit(true);
				return clearCollapseTimer;
			}
			if (!wasStreaming.current) return clearCollapseTimer;
			wasStreaming.current = false;
			if (userToggled.current) return clearCollapseTimer;
			collapseTimer.current = setTimeout(() => {
				collapseTimer.current = undefined;
				commit(false);
			}, AUTO_COLLAPSE_MS);
			return clearCollapseTimer;
		}, [streaming, commit]);

		// A consumer that rewrites the `open` prop moves the panel without going
		// through `commit`, so nothing above reports it. The README promises
		// every change is announced, whichever side caused it.
		const notifyToggle = useEventCallback(onToggle);
		useEffect(() => {
			if (isOpen === lastNotifiedOpen.current) return;
			lastNotifiedOpen.current = isOpen;
			notifyToggle(isOpen);
		}, [isOpen, notifyToggle]);

		// The timer only exists while the trace grows; its last reading survives
		// as the summary duration.
		useEffect(() => {
			if (!streaming) return;
			startElapsed(since ?? Date.now());
			return () => {
				setMeasuredMs(elapsedMsRef.current);
				stopElapsed();
			};
		}, [streaming, since, startElapsed, stopElapsed]);

		const [bodyEl, bodyRef] = useElementRef<HTMLDivElement>();
		const inertRef = useInertAttribute<HTMLDivElement>(!isOpen);
		const composedBodyRef = useComposedRefs<HTMLDivElement>(bodyRef, inertRef);
		useAutoscroll(bodyEl, { enabled: streaming && isOpen, pinOnConnect: true });

		return (
			<div
				ref={ref}
				className={cn(
					"fancy-reasoning-panel border-border bg-card/50 w-full rounded-lg border text-sm",
					className
				)}
			>
				<button
					type="button"
					id={headerId}
					className="text-muted-foreground hover:text-foreground flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left transition-colors"
					aria-expanded={isOpen}
					aria-controls={bodyId}
					onClick={toggle}
				>
					<svg
						className={cn("ft-chevron size-3.5 shrink-0", isOpen && "ft-open")}
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						strokeWidth="2.5"
						strokeLinecap="round"
						strokeLinejoin="round"
						aria-hidden="true"
					>
						<path d="m9 6 6 6-6 6" />
					</svg>
					<span className={cn("text-foreground font-medium", streaming && "ft-shimmer")}>
						{label}
					</span>
					{summary ? <span className="ml-auto text-xs tabular-nums">{summary}</span> : null}
				</button>

				<div className={cn("ft-body", isOpen && "ft-open")}>
					<div className="overflow-hidden">
						{/*
							`inert` goes straight to the node through `useInertAttribute`, never
							as a JSX prop: React 18 drops `inert={true}` and React 19 rejects
							`inert=""`, so no single prop spelling covers this package's peer
							range. The hook emits the same attribute on both.
						*/}
						<div
							ref={composedBodyRef}
							id={bodyId}
							role="group"
							aria-labelledby={headerId}
							className="text-muted-foreground overflow-y-auto px-3 pb-3 leading-relaxed"
							style={{ maxHeight }}
						>
							<StreamText text={text} />
						</div>
					</div>
				</div>
			</div>
		);
	}
);
