// vue/src/cameleon/primitives/Slider.vue
<script lang="ts">
import type { HTMLAttributes } from "vue";

export interface SliderProps {
	error?: boolean;
	class?: HTMLAttributes["class"];
	value?: number;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from "vue";
import { cn } from "../../utils.js";
import { useSkin } from "../context.js";

defineOptions({ name: "Slider", inheritAttrs: false });

const { error = false, class: className } = defineProps<SliderProps>();

// `.number` on the binding reproduces the numeric coercion a range input's
// two-way binding has in the source; the raw DOM value is always a string.
const value = defineModel<number>("value", { default: 50 });

const attrs = useAttrs();
const input = useTemplateRef<HTMLInputElement>("input");
defineExpose({ ref: input });

const ctx = useSkin();
const parts = computed(() => ctx.skin.recipes.slider({ state: error ? "error" : undefined }));
</script>

<template>
	<input
		ref="input"
		type="range"
		v-model.number="value"
		:class="cn(parts.root, className)"
		:aria-invalid="error || undefined"
		v-bind="attrs"
	/>
</template>

// react/src/cameleon/primitives/Slider.tsx
import { forwardRef, type InputHTMLAttributes } from "react";
import { cn } from "../../utils.js";
import { useSkin } from "../context.js";

export interface SliderProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "className" | "type"> {
	error?: boolean;
	className?: string;
	value?: number;
}

export const Slider = forwardRef<HTMLInputElement, SliderProps>(function Slider(
	{ error = false, className, ...rest },
	ref
) {
	const ctx = useSkin();
	const parts = ctx.skin.recipes.slider({ state: error ? "error" : undefined });

	return (
		<input
			type="range"
			ref={ref}
			className={cn(parts.root, className)}
			aria-invalid={error || undefined}
			{...rest}
		/>
	);
});
